spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_59
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

application:
  sync-db: true
