spring.datasource.url=jdbc:postgresql://localhost:5432/todo_59
spring.datasource.username=macbookpro
spring.datasource.password=19801980
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.shell.interactive.enabled=true